const zhDict = {
  "Day": "日",
  "Out": "出",
  "Spending has exceeded income this month.": "这个月的支出超过了收入。",
  "You're using under half your income this month.": "你这个月的收入还不到一半。",
  "Spending is comfortable relative to income this month.": "本月支出相对于收入来说比较舒适。",
  "Spending takes up most of your income this month.": "本月支出占据了你的大部分收入。",
  "Spending is nearly equal to income this month.": "这个月的支出几乎等于收入。",
  "In": "在",
  "Spending share by category": "按类别划分的支出份额",
  "of spending": "的支出",
  "Total spent": "总支出",
  "categories": "类别",
  "Debt share by item": "按项目划分的债务份额",
  "items": "项目",
  "Settings": "设置",
  "Close": "关闭",
  "Goal name": "目标名称",
  "e.g. MacBook, Japan trip...": "例如MacBook，日本之旅...",
  "Color": "颜色",
  "Saved": "已保存",
  "Target": "目标",
  "Save/month": "Save/month",
  "Save changes": "保存更改",
  "Add goal": "添加目标",
  "left": "左",
  "Edit": "编辑",
  "Delete": "删除",
  "Income": "收入",
  "Spending": "支出",
  "Owed to you": "欠你的",
  "You owe": "你欠",
  "Current balance": "当前余额",
  "End-of-month balance": "月末余额",
  "Avg spend/day": "平均支出/天",
  "Projected month-end spend": "预计月末支出",
  "Spend vs last month": "支出与上个月相比",
  "Edit transaction": "编辑交易",
  "Edit expense": "编辑费用",
  "Edit income": "编辑收入",
  "DESCRIPTION": "描述",
  "AMOUNT": "金额",
  "CATEGORY": "类别",
  "DATE": "日期",
  "Previous month": "上个月",
  "Next month": "下个月",
  "Go to transactions": "前往交易",
  "Month note": "月记",
  "Opening balance": "期初余额",
  "Income this month": "本月收入",
  "txns": "交易",
  "/ea": "/ea",
  "Spending this month": "本月支出",
  "Debts & Loans": "债务和贷款",
  "Debt direction": "债务方向",
  "to pay": "支付",
  "to collect": "收集",
  "others": "其他",
  "other creditors": "其他债权人",
  "No one owes you yet": "还没有人欠你的",
  "You don't owe anyone": "你不欠任何人",
  "This month's note": "本月笔记",
  "Cancel": "取消",
  "Save": "保存",
  "Quick note about this month…": "关于本月的快速说明...",
  "Debts & Loans detail": "债务和贷款详情",
  "Debt-free!": "Debt-free!",
  "No open debts": "无未清债务",
  "Go to manage page": "进入管理页面",
  "Add transaction": "添加交易",
  "Expense": "费用",
  "History": "历史",
  "QUICK TEMPLATES": "快速模板",
  "Done": "完成",
  "Template name…": "模板名称...",
  "Tap Edit to add quick templates.": "点击编辑以添加快速模板。",
  "e.g. Lunch, Grab, books…": "例如午餐、外卖、书籍……",
  "No expenses yet": "还没有任何费用",
  "Add your first transaction this month": "添加您本月的第一笔交易",
  "TODAY": "今天",
  "YESTERDAY": "昨天",
  "e.g. Salary, transfer…": "例如工资、转会……",
  "No income yet": "还没有收入",
  "Add your first income this month": "添加您本月的第一笔收入",
  "transactions": "交易",
  "No transactions": "没有交易",
  "No transactions in this category": "该类别没有交易",
  "Budget": "预算",
  "Add budget": "添加预算",
  "Add": "添加",
  "Add new budget": "添加新预算",
  "All categories already have a budget.": "所有类别都已经有预算。",
  "Category": "类别",
  "Limit / month": "限额/月",
  "No budgets": "没有预算",
  "Tap + Add to set spending limits": "点击 + 添加以设置支出限额",
  "Avg/day": "Avg/day",
  "Avg/week": "Avg/week",
  "Spending by category": "按类别支出",
  "No spending yet": "还没有消费",
  "Add transactions to see analysis": "添加交易以查看分析",
  "Spending by day": "按天支出",
  "Spending by month": "按月支出",
  "Last 6 months": "过去 6 个月",
  "Month": "月份",
  "No data yet": "还没有数据",
  "Add transactions to see cash flow": "添加交易以查看现金流",
  "Today": "今天",
  "Yesterday": "昨天",
  "Category name can't be empty": "类别名称不能为空",
  "Category names must be unique": "类别名称必须是唯一的",
  "“Thu nhập” (Income) is reserved and can't be used for an expense category": "“Thu nhập”（收入）已保留，不能用于费用类别",
  "Edit categories": "编辑类别",
  "Rename, change icon/color, or add a new category": "重命名、更改图标/颜色或添加新类别",
  "Icon": "图标",
  "Category name": "类别名称",
  "System category — can't be renamed": "系统类别 - 无法重命名",
  "Change color": "改变颜色",
  "transactions using this": "使用此交易",
  "System category — can't be deleted": "系统类别-无法删除",
  "System category": "系统类别",
  "Delete category": "删除类别",
  "Color ": "颜色",
  "Edit quick templates": "编辑快速模板",
  "Templates prefill the form with a single tap": "只需点击一下模板即可预填写表单",
  "No templates yet": "还没有模板",
  "Tap Add to create your first one": "点击“添加”来创建您的第一个",
  "Template name": "模板名称",
  "Delete template": "删除模板",
  "Sort": "排序",
  "TRANSACTIONS": "交易",
  "Quick templates": "快速模板",
  "New template": "新模板",
  "Description": "描述",
  "e.g. Salary, transfer...": "例如工资、转会...",
  "e.g. Lunch, Grab, books...": "例如午餐，外卖，书籍……",
  "Amount": "金额",
  "Date": "日期",
  "Added!": "Added!",
  "TRANSACTION HISTORY": "交易记录",
  "From": "来自",
  "To": "至",
  "Clear filters": "清除过滤器",
  "No transactions yet": "还没有交易",
  "No results": "没有结果",
  "Try a different keyword or clear the filters": "尝试不同的关键字或清除过滤器",
  "DEBT LEDGER": "债务分类账",
  "Settled": "已定居",
  "debts": "债务",
  "Record a new debt": "记录新债务",
  "Person": "人",
  "e.g. Nam, Han...": "例如南、韩...",
  "Type": "类型",
  "I owe them": "我欠他们的",
  "They owe me": "他们欠我的",
  "Note": "注意事项",
  "Optional": "可选",
  "DEBT HISTORY": "债务历史",
  "All": "全部",
  "I owe": "我欠",
  "Owed to me": "欠我的",
  "No debts": "无债务",
  "Nice! You're debt-free.": "不错！你没有债务。",
  "Reopen": "重新开放",
  "Pay": "支付",
  "Collect": "收集",
  "BUDGET": "预算",
  "Total": "总计",
  "Spent": "已用",
  "of budget": "预算的",
  "Remaining": "剩余",
  "unspent": "未花费的",
  "over budget": "超出预算",
  "Edit limit": "编辑限制",
  "Add / update limit": "添加/更新限制",
  "Set a monthly spending cap for each category": "为每个类别设置每月支出上限",
  "BUDGET LIST": "预算清单",
  "No budgets yet": "还没有预算",
  "Add your first category above to start controlling spending": "添加上面的第一个类别以开始控制支出",
  "Over": "结束",
  "Left": "左",
  "used": "使用过的",
  "Avg": "平均",
  "/day": "/day",
  "/week": "/week",
  "Auto-saves as you type": "键入时自动保存",
  "Financial notes": "财务笔记",
  "Jot down what to remember: rent, upcoming payments, spending decisions, savings goals...": "记下要记住的内容：租金、即将付款、支出决定、储蓄目标......",
  "characters": "人物",
  "Saved alongside your financial data": "与您的财务数据一起保存",
  "SETTINGS": "设置",
  "Account": "账户",
  "Admin": "管理员",
  "Log out": "退出",
  "Appearance": "外观",
  "Light": "光",
  "Dark": "黑暗",
  "Language": "语言",
  "Vietnamese": "越南语",
  "English": "英语",
  "Accounts": "账户",
  "Total balance": "总余额",
  "Total income": "总收入",
  "Total expense": "总费用",
  "Account management": "账户管理",
  "Refresh": "刷新",
  "Couldn't load the account list": "无法加载帐户列表",
  "Firestore is blocking reads of other accounts' data. Grant the owner read access in your Firestore Rules, then press Refresh:": "Firestore 正在阻止读取其他帐户的数据。在 Firestore 规则中授予所有者读取权限，然后按刷新：",
  "Error code": "错误代码",
  "Loading…": "加载中...",
  "No accounts yet": "还没有账户",
  "Search by email or UID…": "通过电子邮件或 UID 搜索...",
  "accounts": "账户",
  "Balance": "平衡",
  "Owes": "欧斯",
  "Lent": "四旬期",
  "Txns": "交易",
  "Created": "已创建",
  "(no email)": "（没有电子邮件）",
  "That email address looks invalid.": "该电子邮件地址看起来无效。",
  "Wrong email or password.": "电子邮件或密码错误。",
  "This email already has an account.": "该电子邮件已有一个帐户。",
  "Password should be at least 6 characters.": "密码应至少包含 6 个字符。",
  "You closed the sign-in window.": "您关闭了登录窗口。",
  "This sign-in provider isn't enabled in Firebase.": "Firebase 中未启用此登录提供商。",
  "Couldn't sign in, please try again.": "无法登录，请重试。",
  "Enter your email first, then we'll send a reset link.": "首先输入您的电子邮件，然后我们将发送重置链接。",
  "A password reset email has been sent if the account exists.": "如果帐户存在，则已发送密码重置电子邮件。",
  "Create account": "创建帐户",
  "Sign in": "登录",
  "Your data is saved to your own private account.": "您的数据将保存到您自己的私人帐户中。",
  "Manage your spending, budgets and financial data.": "管理您的支出、预算和财务数据。",
  "Display name": "显示名称",
  "Your name": "你的名字",
  "Password": "密码",
  "At least 6 characters": "至少 6 个字符",
  "Hide password": "隐藏密码",
  "Show password": "显示密码",
  "Working...": "Working...",
  "Sign in with Google": "使用 Google 登录",
  "Already have an account? Sign in": "已经有帐户？登录",
  "Create one": "创建一个",
  "Forgot password": "忘记密码",
  "Couldn't connect to the database — showing sample data. DON'T add/edit transactions right now. Your real data is still safe on the server; check the connection/Firestore and reload.": "无法连接到数据库 — 显示示例数据。现在不要添加/编辑交易。您的真实数据在服务器上仍然安全；检查连接/Firestore 并重新加载。",
  "Couldn't connect to the database — showing a local backup. Changes won't sync until the connection is restored.": "无法连接到数据库 — 显示本地备份。在连接恢复之前，更改不会同步。"
};